"""initial schema

Revision ID: eb5fc5ddaf91
Revises: 
Create Date: 2026-06-17 18:25:40.349651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5fc5ddaf91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legacy_csv_id', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('birthdate', sa.String(length=16), nullable=True),
    sa.Column('nationality', sa.String(length=8), nullable=True),
    sa.Column('traveldoc', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('email_pass', sa.String(length=128), nullable=True),
    sa.Column('proxy_last_used', sa.String(length=256), nullable=True),
    sa.Column('proxy_idx', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.String(length=32), nullable=True),
    sa.Column('last_login', sa.String(length=32), nullable=True),
    sa.Column('appointment_ref', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_status'), 'account', ['status'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('booking_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('target_posto_id', sa.String(length=16), nullable=False),
    sa.Column('target_nationality', sa.String(length=8), nullable=False),
    sa.Column('target_residence', sa.String(length=8), nullable=False),
    sa.Column('max_lifetime', sa.Float(), nullable=False),
    sa.Column('max_slot_retries', sa.Integer(), nullable=False),
    sa.Column('login_concurrency', sa.Integer(), nullable=False),
    sa.Column('apply_concurrency', sa.Integer(), nullable=False),
    sa.Column('scouts_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('geo', sa.String(length=8), nullable=True),
    sa.Column('cursor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_pool_name'), 'proxy_pool', ['name'], unique=True)
    op.create_table('telegram_chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('notify_on_success', sa.Boolean(), nullable=False),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('booking_event_proxy_pool',
    sa.Column('booking_event_id', sa.Integer(), nullable=False),
    sa.Column('proxy_pool_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_event_id'], ['booking_event.id'], ),
    sa.ForeignKeyConstraint(['proxy_pool_id'], ['proxy_pool.id'], ),
    sa.PrimaryKeyConstraint('booking_event_id', 'proxy_pool_id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proxy_pool_id', sa.Integer(), nullable=False),
    sa.Column('connection_string', sa.String(length=512), nullable=False),
    sa.Column('exit_ip_cached', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_account_id', sa.Integer(), nullable=True),
    sa.Column('burned_until', sa.String(length=16), nullable=True),
    sa.Column('is_rotating', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proxy_pool_id'], ['proxy_pool.id'], ),
    sa.ForeignKeyConstraint(['used_by_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_string')
    )
    op.create_index(op.f('ix_proxy_proxy_pool_id'), 'proxy', ['proxy_pool_id'], unique=False)
    op.create_table('schedule_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_event_id', sa.Integer(), nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('fired', sa.Boolean(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_event_id'], ['booking_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_event_id')
    )
    op.create_index(op.f('ix_schedule_entry_fire_at'), 'schedule_entry', ['fire_at'], unique=False)
    op.create_table('session_checkpoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('proxy', sa.String(length=512), nullable=True),
    sa.Column('cookies_json', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.String(length=32), nullable=False),
    sa.Column('posto_id', sa.String(length=16), nullable=True),
    sa.Column('posto_pdf', sa.String(length=16), nullable=True),
    sa.Column('nationality', sa.String(length=8), nullable=True),
    sa.Column('residence', sa.String(length=8), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('worker_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_event_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['booking_event_id'], ['booking_event.id'], ),
    sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_run_account_id'), 'worker_run', ['account_id'], unique=False)
    op.create_index(op.f('ix_worker_run_booking_event_id'), 'worker_run', ['booking_event_id'], unique=False)
    op.create_table('appointment_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('period_id', sa.String(length=16), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('appointment_ref', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_run_id'], ['worker_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_result_worker_run_id'), 'appointment_result', ['worker_run_id'], unique=False)
    op.create_table('captcha_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_run_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('token_score', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_run_id'], ['worker_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_run_id', sa.Integer(), nullable=True),
    sa.Column('booking_event_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_event_id'], ['booking_event.id'], ),
    sa.ForeignKeyConstraint(['worker_run_id'], ['worker_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_booking_event_id'), 'event_log', ['booking_event_id'], unique=False)
    op.create_index(op.f('ix_event_log_created_at'), 'event_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_log_worker_run_id'), 'event_log', ['worker_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_worker_run_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_created_at'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_booking_event_id'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('captcha_usage_log')
    op.drop_index(op.f('ix_appointment_result_worker_run_id'), table_name='appointment_result')
    op.drop_table('appointment_result')
    op.drop_index(op.f('ix_worker_run_booking_event_id'), table_name='worker_run')
    op.drop_index(op.f('ix_worker_run_account_id'), table_name='worker_run')
    op.drop_table('worker_run')
    op.drop_table('session_checkpoint')
    op.drop_index(op.f('ix_schedule_entry_fire_at'), table_name='schedule_entry')
    op.drop_table('schedule_entry')
    op.drop_index(op.f('ix_proxy_proxy_pool_id'), table_name='proxy')
    op.drop_table('proxy')
    op.drop_table('booking_event_proxy_pool')
    op.drop_table('telegram_chat')
    op.drop_index(op.f('ix_proxy_pool_name'), table_name='proxy_pool')
    op.drop_table('proxy_pool')
    op.drop_table('booking_event')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_status'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
